In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[416, 66, 7161, 1416],
 [416, 66, 7161, 8868],
 [416, 324, 7161, 121],
 [7424, 8014, 9226, 798, 455],
 [7424, 8014, 9226, 798, 7173],
 [3615, 416, 5720, 7161, 2369],
 [4745, 8404, 967, 798]]

In [6]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  416   66 7161 1416]
 [   0    0    0    0  416   66 7161 8868]
 [   0    0    0    0  416  324 7161  121]
 [   0    0    0 7424 8014 9226  798  455]
 [   0    0    0 7424 8014 9226  798 7173]
 [   0    0    0 3615  416 5720 7161 2369]
 [   0    0    0    0 4745 8404  967  798]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 118ms/step


array([[[-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
          3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
         -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
          3.27800252e-02],
        [-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
          3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
         -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
          3.27800252e-02],
        [-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
          3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
         -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
          3.27800252e-02],
        [-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
          3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
         -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
          3.27800252e-02],
        [ 3.56466062e-02,  3.92091908e-02, -2.71404032e-02,
         -3.43931317e-02,  4.39293496e-02,  3.00599448e-02,
         -1.43167265e-02, -1.96042899e-02, -4.857413

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0,  416,   66, 7161, 1416], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 68ms/step


array([[-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
         3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
        -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
         3.27800252e-02],
       [-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
         3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
        -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
         3.27800252e-02],
       [-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
         3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
        -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
         3.27800252e-02],
       [-2.00194959e-02,  6.94106892e-03,  1.54380314e-02,
         3.17534544e-02, -2.98231374e-02,  3.77000608e-02,
        -1.68293826e-02, -1.15163215e-02, -3.58455405e-02,
         3.27800252e-02],
       [ 3.56466062e-02,  3.92091908e-02, -2.71404032e-02,
        -3.43931317e-02,  4.39293496e-02,  3.00599448e-02,
        -1.43167265e-02, -1.96042899e-02, -4.85741384e-02,
        -4.